############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1


[[main]]
name = "  "
url = "intelligentradio/"
weight = 1

[[main]]
name = "   "
url = "intelligentradio/"
weight = 2

[[main]]
name = "    "
url = "intelligentradio/"
weight = 2.5
[[main]]
name = "     "
url = "intelligentradio/"
weight = 2.6

[[main]]
name = "Intelligent Radio"
url = "intelligentradio/"
weight = 3

#####################

[[main]]
name = "Company"
url = "compamy/"
hasChildren = true
weight = 4

[[main]]
parent = "Company"
weight = 1
name = "About Qoherent"
url = "company/"

[[main]]
parent = "Company"
weight = 2
name = "News"
url = "categories/news/"

## for later
# [[main]]
# parent = "Company"
# name = "Open Source"
# weight = 3
# url = "open-source/"

[[main]]
parent = "Company"
name = "Careers"
weight = 4
url = "careers/"

#####################
[[main]]
name = "Products"
url = "radiointelligenceapps/"
hasChildren = true
weight = 5

[[main]]
parent = "Products"
weight = 1
name = "RIA Suite"
url = "radiointelligenceapps-suite/"

# ## for later
# [[main]]
# parent = "Products"
# weight = 2
# name = "RIA Models"
# url = "radiointelligenceapps-models/"

# ## for later
# [[main]]
# parent = "Products"
# weight = 3
# name = "RIA Inference"
# url = "rie/"

[[main]]
parent = "Products"
weight = 4
name = "RIARAN"
url = "radiointelligenceapps-ran/"

#####################
[[main]]
name = "Services"
url = "prototyping/"
hasChildren = true
weight = 6

[[main]]
parent = "Services"
weight = 1
name = "ML Prototyping & Testbeds"
url = "prototyping/"

# ##for later
# [[main]]
# parent = "Services"
# weight = 2
# name = "Testbeds"
# url = "testbeds/"

[[main]]
parent = "Services"
weight = 3
name = "Custom Datasets"
url = "custom-datasets/"

#####################
[[main]]
name = "Resources"
url = "resources/"
hasChildren = true
weight = 7

[[main]]
parent = "Resources"
weight = 1
name = "Tech Blog"
url = "categories/tech-blog/"

[[main]]
parent = "Resources"
weight = 2
name = "Articles"
url = "categories/articles/"

[[main]]
parent = "Resources"
weight = 3
name = "Downloads"
url = "downloads/"

# ## For larer
# [[main]]
# parent = "Resources"
# weight = 4
# name = "Docs"
# url = "docs/"

# Remove when done using this

[[main]]
parent = "Resources"
name = "Elements"
url = "elements/"
weight = 5


#####################################
# # footer menu
[[footer]]
name = "Company"
url = "company/"
weight = 1

##Will change these later based on what we want

# [[footer]]
# name = "Elements"
# url = "elements/"
# weight = 2

[[footer]]
name = "Careers"
weight = 5
url = "careers/"

[[footer]]
name = "News"
url = "categories/news/"
hasChildren = true
weight = 7

################################################
# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3

# [[main]]
# name = " "
# weight = 5
# hasChildren = true

# [[main]]
# parent = "Company"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Company"
# name = "404 Page"
# url = "404/"

# [[main]]
# name = "Radio Intelligence Apps"
# url = "radiointelligence/"
# weight = 4

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 4



# [[main]]
# weight = 5
# name = "Pages"
# hasChildren = true

# [[main]]
# parent = "About"
# name = "News & Articles"
# url = "blog/"